## Домашнее задание

В этой тетрадке вам предлагается реализовать задания при помощи библиотеки numpy. Крайне желательно при выполнении разных заданий не использовать циклы. Если вы не понимаете, как выполнить конкретную задачу без циклов - убирайте их постепенно, разбейте выполнение задачи на этапы и постепенно векторизуйте каждый этап.

Если вам непонятно, как выполнить ту или иную операцию - не стесняйтесь гуглить, если над вами повис дедлайн, а вы всё ещё на чём-то застряли - пишите преподу/в чат, это ок.

**Обсудить решение лучше и сделать в итоге хоть что-то гораздо лучше, чем скатать чужой код или сдать пустую тетрадку.**

In [1]:
import numpy as np

# Это для 21 задания
import warnings
warnings.filterwarnings("ignore")

### Drill (1 балл)

Задание 1.

Инициализируйте нулями массивы следующих форм:

* (5)
* (5, 1)
* (10, 2)
* (3, 6, 2)
* (4, 3, 2, 1)

In [2]:
# Ваш код
arr_1_zeros = np.zeros(5)
arr_2_zeros = np.zeros(shape = (5, 1))
arr_3_zeros = np.zeros(shape = (10, 2))
arr_4_zeros = np.zeros(shape = (3, 6, 2))
arr_5_zeros = np.zeros(shape = (4, 3, 2, 1))

Задание 2.

Инициализируйте единицами массивы таких же форм и приведите их к целочисленному виду:

In [3]:
# Ваш код
arr_1_ones = np.ones(5, dtype=int)
arr_2_ones = np.ones(shape = (5, 1), dtype=int)
arr_3_ones = np.ones(shape = (10, 2), dtype=int)
arr_4_ones = np.ones(shape = (3, 6, 2), dtype=int)
arr_5_ones = np.ones(shape = (4, 3, 2, 1), dtype=int)

Задание 3.

Выполните для векторов выше `reshape` в
* 2 произвольных компоненты
* 3 произвольных компоненты
* 4 произвольных компоненты

In [4]:
# Ваш код
arr_3_ones = arr_3_ones.reshape((20, 1))
arr_4_ones = arr_4_ones.reshape((3, 3, 4))
arr_5_ones = arr_5_ones.reshape((1, 2, 3, 4))

Задание 4.

Для вектора ниже посчитайте его
* Максимум по 1 оси
* Минимум по 0 оси
* Сумму по всем осям
* Среднее по 0 оси
* Медиану по 1 оси

In [5]:
v = np.random.randint(0, 9, size=(5, 7))

In [6]:
v

array([[4, 6, 1, 2, 8, 6, 8],
       [8, 3, 4, 6, 1, 8, 7],
       [0, 6, 4, 1, 1, 4, 6],
       [7, 6, 1, 7, 5, 1, 4],
       [7, 0, 7, 7, 1, 3, 1]])

In [7]:
# Ваш код
maximum = v.max(axis = 1)
minimum = v.min(axis = 0)
summa = v.sum()
mean = v.mean(axis = 0)
median = np.median(v, axis = 1)

print("Максимум по 1 оси: ", maximum) 
print("Минимум по 0 оси: ", minimum)
print("Сумма по всем осям: ", summa)
print("Среднее по 0 оси: ", mean)
print("Медиана по 1 оси: ", median)

Максимум по 1 оси:  [8 8 6 7 7]
Минимум по 0 оси:  [0 0 1 1 1 1 1]
Сумма по всем осям:  151
Среднее по 0 оси:  [5.2 4.2 3.4 4.6 3.2 4.4 5.2]
Медиана по 1 оси:  [6. 6. 4. 5. 3.]


Задание 6.

Для всё того же вектора `v` выведите
* Его shape
* 0 компоненту его "формы"
* 1 компоненту его "формы"

In [8]:
# Ваш код'
print(v.shape)
print(v.shape[0], v.shape[1])

(5, 7)
5 7


Задание 7.

Для этого же вектора выведите
* Все числа больше 5
* Все числа меньше 7 в обратном порядке
* Все числа больше 3, которые делятся на 4 без остатка
* Все числа, остаток от деления на 5 которых равен 3
* Индекс максимума
* Индекс минимума
* Cписок с индексами элементов отсортированного массива в исходном (неотсортированном)

In [9]:
# Ваш код
print(v[v > 5])
print(v[v < 7][::-1])
print(v[(v > 3) & (v % 4 == 0)])
print(v[(v % 5 == 3)])
print(np.argmin(v))
print(np.argmax(v))
print(np.argsort(v, axis = None))

[6 8 6 8 8 6 8 7 6 6 7 6 7 7 7 7]
[1 3 1 0 4 1 5 1 6 6 4 1 1 4 6 0 1 6 4 3 6 2 1 6 4]
[4 8 8 8 4 8 4 4 4]
[8 8 8 3 8 3]
14
4
[29 14 17 32 26 23 18 11 34  2  3  8 33  9 27 19  0 16 25  1 10 22 15 20
  5 24 28 30 31 13 21  4 12  7  6]


Задание 8.

Выполните следующие операции над вектором (независимо, не обязательно делать это в последовательности):
* Умножьте его на 3
* Разделите на 7
* Возведите в степень $\frac{2}{3}$
* Посчитайте $\sin$ от него
* Посчитайте $\log$ от него

In [10]:
# Ваш код
print(v * 3)
print('-' * 20)
print(v / 7)
print('-' * 20)
print(np.power(v, 2/3))
print('-' * 20)
print(np.sin(v))
print('-' * 20)
print(np.log(v))

[[12 18  3  6 24 18 24]
 [24  9 12 18  3 24 21]
 [ 0 18 12  3  3 12 18]
 [21 18  3 21 15  3 12]
 [21  0 21 21  3  9  3]]
--------------------
[[0.57142857 0.85714286 0.14285714 0.28571429 1.14285714 0.85714286
  1.14285714]
 [1.14285714 0.42857143 0.57142857 0.85714286 0.14285714 1.14285714
  1.        ]
 [0.         0.85714286 0.57142857 0.14285714 0.14285714 0.57142857
  0.85714286]
 [1.         0.85714286 0.14285714 1.         0.71428571 0.14285714
  0.57142857]
 [1.         0.         1.         1.         0.14285714 0.42857143
  0.14285714]]
--------------------
[[2.5198421  3.30192725 1.         1.58740105 4.         3.30192725
  4.        ]
 [4.         2.08008382 2.5198421  3.30192725 1.         4.
  3.65930571]
 [0.         3.30192725 2.5198421  1.         1.         2.5198421
  3.30192725]
 [3.65930571 3.30192725 1.         3.65930571 2.92401774 1.
  2.5198421 ]
 [3.65930571 0.         3.65930571 3.65930571 1.         2.08008382
  1.        ]]
--------------------
[[-0.756802

### Разные инициализации + индексирование (3 балла)

Задание 9.

Необходимо построить квадрат $3 \times 3$ из нечётных чисел

In [11]:
# Ваш код
np.arange(1, 19, 2).reshape((3, 3))

array([[ 1,  3,  5],
       [ 7,  9, 11],
       [13, 15, 17]])

Задание 10.

Необходимо построить квадрат $4 \times 4$ из четных чисел в обратном порядке

In [12]:

# Я считал ноль за чётное число
np.arange(30, -1, -2).reshape((4, 4))

array([[30, 28, 26, 24],
       [22, 20, 18, 16],
       [14, 12, 10,  8],
       [ 6,  4,  2,  0]])

Задание 11.

Необходимо построить сетку координат $11 \times 11$ с точкой $(0,0)$ в центре и шагом $0.1$ между клетками

In [13]:
# Ваш код
x = np.arange(-6, 6.1, 0.1).reshape((11, 11))

# Выведем значение в центре
print(round(x[5, 5], 5))

-0.0


Задание 12.

Замощение сетки $8\times8$ при помощи $0$ и $1$ в шахматном порядке, клетка с индексом $(0,0)$ замощается $1$

In [14]:
# Ваш код

# Делаем сдвиг на 1, чтобы сделать размощение по заданию (индекс (0, 0) - сверху слева)
np.apply_along_axis(lambda x: (x + x // 8 + 1) % 2, -1, np.arange(0, 64, 1)).reshape((8, 8))

array([[1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1]])

Задание 13.

То же замощение, но клетка с индексом $(0,0)$ замощается $0$

In [15]:
# Ваш код
np.apply_along_axis(lambda x: (x + x // 8) % 2, -1, np.arange(0, 64, 1)).reshape((8, 8))

array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0]])

Задание 14.

Необходимо построить нижне-треугольную матрицу переменного размера (задается передачей параметра в функцию). Это единичная матрица,замощённая $1$ под главной диагональю

In [16]:
# Ваш код
def create_low_matrix(size):
  return np.apply_along_axis(lambda x: (x % size <= x // size), -1, np.arange(0, size * size, 1)).\
                                                                                                  reshape((size, size)).\
                                                                                                  astype(int)

In [17]:
create_low_matrix(5)

array([[1, 0, 0, 0, 0],
       [1, 1, 0, 0, 0],
       [1, 1, 1, 0, 0],
       [1, 1, 1, 1, 0],
       [1, 1, 1, 1, 1]])

Задание 15.

Необходимо построить верхне-треугольную матрицу переменного размера. Это единичная матрица, замощённая $1$ над главной диагональю

In [18]:
# Ваш код
def create_high_matrix(size):
  return create_low_matrix(size).T  #  ))))))))

def create_high_matrix_1(size):
    return np.apply_along_axis(lambda x: (x % size >= x // size), -1, np.arange(0, size * size, 1)).\
                                                                                                  reshape((size, size)).\
                                                                                                  astype(int)

In [19]:
create_high_matrix(5)

array([[1, 1, 1, 1, 1],
       [0, 1, 1, 1, 1],
       [0, 0, 1, 1, 1],
       [0, 0, 0, 1, 1],
       [0, 0, 0, 0, 1]])

In [20]:
create_high_matrix_1(5)

array([[1, 1, 1, 1, 1],
       [0, 1, 1, 1, 1],
       [0, 0, 1, 1, 1],
       [0, 0, 0, 1, 1],
       [0, 0, 0, 0, 1]])

Задание 16.

Необходимо построить матрицу, в которой единицы стоят на побочной диагонали (идущей из левого нижнего угла в правый верхний), в остальных местах стоят $0$

In [21]:
# Ваш код
def create_matr(size):
  return np.rot90(np.eye(size)).astype(int)

create_matr(5)

array([[0, 0, 0, 0, 1],
       [0, 0, 0, 1, 0],
       [0, 0, 1, 0, 0],
       [0, 1, 0, 0, 0],
       [1, 0, 0, 0, 0]])

### Операции + аггрегации (3 балла)

Задание 17.

Дана выборка $\{X_i\}$ некоторой случайной величины $X$, необходимо оценить
* Математическое ожидание $E[X] = \frac{1}{N}\sum_{i=1}^N X_i$ этой случайной величины
* Дисперсию $D[X] = \frac{1}{N}\sum_{i=1}^N (X_i - E[X])^2$ этой случайной величины

In [22]:
def expected_value(x):
    assert len(x) > 0
    return sum(x) / len(x)


def dispersion(x):
    assert len(x) > 0
    d = 0
    e = expected_value(x)
    for x_i in x:
        d += (x_i - e) ** 2
    return d / len(x)

In [23]:
def expected_value_np(x):
    return np.mean(x)

In [24]:
def dispersion_np(x):
    return np.mean(np.power(x - np.mean(x), 2))

In [25]:
np.testing.assert_array_equal(expected_value([1]), expected_value_np(np.array([1])))
np.testing.assert_array_equal(expected_value([3, 4]), expected_value_np(np.array([3, 4])))
np.testing.assert_array_equal(expected_value([-1, 0, 1]), expected_value_np(np.array([-1, 0, 1])))
np.testing.assert_array_equal(expected_value([-99, -98]), expected_value_np(np.array([-99, -98])))

np.testing.assert_array_equal(dispersion([1]), dispersion_np(np.array([1])))
np.testing.assert_array_equal(dispersion([3, 4]), dispersion_np(np.array([3, 4])))
np.testing.assert_array_equal(dispersion([-1, 0, 1]), dispersion_np(np.array([-1, 0, 1])))
np.testing.assert_array_equal(dispersion([-99, -98]), dispersion_np(np.array([-99, -98])))

Задание 18.

Даны два вектора $y_1$ и $y_2$, нужно посчитать среднее арифметическое квадратов разностей их значений

In [26]:
def mean_square_difference(y1, y2):
    assert len(y1) == len(y2) and len(y1) > 0
    # Здесь и далее эти проверки !не нужно! дублировать в свои функции; Здесь они для того, чтобы лишний раз подчеркнуть валидность входных данных
    s = 0
    for i in range(len(y1)):
        s += (y1[i] - y2[i]) ** 2
    return s / len(y1)

In [27]:
def mean_square_difference_np(y1, y2):
    return np.mean(np.power((y1 - y2), 2))

In [28]:
assert mean_square_difference([1], [1]) == mean_square_difference_np(np.array([1]), np.array([1]))
assert mean_square_difference([1, 2], [1, 2]) == mean_square_difference_np(np.array([1, 2]), np.array([1, 2]))
assert mean_square_difference([-1, 1], [0, 0]) == mean_square_difference_np(np.array([-1, 1]), np.array([0, 0]))
assert mean_square_difference([-3, -2, 0, 1, 4], [-2, -2, -1, -1, 5]) == mean_square_difference_np(np.array([-3, -2, 0, 1, 4]), np.array([-2, -2, -1, -1, 5]))

Задание 19.

Даны два вектора $y_1$ и $y_2$, нужно посчитать среднее арифметическое модулей разностей их значений

In [29]:
def mean_abs_difference(y1, y2):
    assert len(y1) == len(y2) and len(y1) > 0
    s = 0
    for i in range(len(y1)):
        s += abs(y1[i] - y2[i])
    return s / len(y1)

In [30]:
def mean_abs_difference_np(y1, y2):
    return np.mean(np.abs(y1 - y2))

In [31]:
assert mean_abs_difference([1], [1]) == mean_abs_difference_np(np.array([1]), np.array([1]))
assert mean_abs_difference([1, 2], [1, 2]) == mean_abs_difference_np(np.array([1, 2]), np.array([1, 2]))
assert mean_abs_difference([-1, 1], [0, 0]) == mean_abs_difference_np(np.array([-1, 1]), np.array([0, 0]))
assert mean_abs_difference([-3, -2, 0, 1, 4], [-2, -2, -1, -1, 5]) == mean_abs_difference_np(np.array([-3, -2, 0, 1, 4]), np.array([-2, -2, -1, -1, 5]))

Задание 20.

Даны два вектора $y_1$ и $y_2$, в которых присутствуют только $0$ и $1$. Необходимо посчитать вероятность совпадения - в скольких точках значения двух векторов совпадают

In [32]:
def matching_proba(y1, y2):
    assert len(y1) == len(y2) and len(y1) > 0
    assert len(set(y1)) <= 2
    assert len(set(y2)) <= 2
    assert 0 in set(y1) or 1 in set(y1) or (0 in set(y1) and 1 in set(y1))
    assert 0 in set(y2) or 1 in set(y2) or (0 in set(y2) and 1 in set(y2))

    return sum([y1[i] == y2[i] for i in range(len(y1))]) / len(y1)

In [33]:
def matching_proba_np(y1, y2):
    return np.sum((y1 == y2).astype(int)) / y1.shape[0]

In [34]:
np.testing.assert_array_equal(matching_proba([0, 1], [1, 0]), matching_proba_np(np.array([0, 1]), np.array([1, 0])))
np.testing.assert_array_equal(matching_proba([0, 1, 0, 1], [0, 0, 1, 1]), matching_proba_np(np.array([0, 1, 0, 1]), np.array([0, 0, 1, 1])))
np.testing.assert_array_equal(matching_proba([0, 0, 1, 1], [0, 0, 1, 1]), matching_proba_np(np.array([0, 0, 1, 1]), np.array([0, 0, 1, 1])))

Задание 21.

Даны два вектора: $y_1$, $y_2$. В $y_1$ и $y_2$ присутствуют только $0$ и $1$.

* Необходимо найти границы (индексы), такие, что если мы разделим какой-то из них оба вектора, то в левой части пересекающихся в $y_1$ и $y_2$ нулей будет больше, чем единиц, а в правой - наоборот. Если какая-то из частей не содержит элементов вовсе, то будем считать, что она подходит под условие.

In [35]:
def find_thresholds(y1, y2, debug=False):
    assert len(y1) == len(y2) and len(y1) > 0
    n = len(y1)
    matching_zeros = [1 if y1[i] == y2[i] == 0 else 0 for i in range(n)]
    matching_ones = [1 if y1[i] == y2[i] == 1 else 0 for i in range(n)]
    res = []
    if sum(matching_ones) / n > 0.5:
        res.append(0)
    for i in range(1, n):
        if debug: # если вам непонятна логика работы этой функции, передайте третьим аргументом True
            print(matching_zeros[:i], matching_ones[i:], i)
        if sum(matching_zeros[:i]) / i > 0.5 and sum(matching_ones[i:]) / (n - i) > 0.5:
            res.append(i)
    if sum(matching_zeros) / n > 0.5:
        res.append(n)
    return res

In [36]:
'''
1. Решения, реализованные обычными средствами, не соответствуют условию
   Поэтому реализация на numpy скорее не выполняет задачу, а выполняет действия для того же ответа, что и в обычной реализации
   Внизу через ячейку я приложил функцию, которая действительно решает задачу по условию.
2. Посмотреть на бумаге, как это работает, и почему можно на github/prianechka

По решению:
3. Если сложить два массива, то в результирующем массиве можно понять, что:
   если элемент == 2 -> совпало по единицам
   если элемент == 0 -> совпало по нулям
   если элемент == 1 -> не совпало
  
4. Формализация задачи сводится к тому, чтобы посчитать количество двоек и нулей по каждой стороне
   и для каждого разбиения посмотреть, где вероятность нуля слева от разбиения > 0.5 (реализация на обычном именно такая, но это не соответствует условию)
   и вероятность двойки справа от разбиения тоже > 0.5 
   
'''
def find_thresholds_np(y1, y2):
  # Разбиений у нас может быть N + 1, где N - размер массива
  result = np.arange(y1.shape[0] + 1)

  arr = y1 + y2
  arr_0 = (arr == 0).astype(int)
  arr_2 = (arr == 2).astype(int)

  N0 = arr_0.sum()
  N2 = arr_2.sum()

  arr_1 = np.cumsum(arr_0)
  arr_2 = np.cumsum(arr_2)
  arr_4 = N2 - arr_2

  arr_zeros = np.hstack((np.array([0]), arr_1))
  arr_ones = np.hstack((np.array([N2]), arr_4))

  arr_prob_1 = np.nan_to_num((arr_ones / result[::-1]), nan=1)
  arr_prob_0 = np.nan_to_num((arr_zeros / result), nan=1)

  return result[(arr_prob_1 > 0.5) & (arr_prob_0 > 0.5)]

In [37]:
def right_decision_np(y1, y2):
  # Разбиений у нас может быть N + 1, где N - размер массива
  result = np.arange(y1.shape[0] + 1)

  arr = y1 + y2
  arr_0 = (arr == 0).astype(int)
  arr_2 = (arr == 2).astype(int)

  N0 = arr_0.sum()
  N2 = arr_2.sum()

  arr_1 = np.cumsum(arr_0)
  arr_2 = np.cumsum(arr_2)
  arr_3 = N0 - arr_1
  arr_4 = N2 - arr_2

  arr_zeros = np.hstack((np.array([0]), arr_1))
  arr_ones = np.hstack((np.array([N2]), arr_4))

  return result[(arr_1 > arr_2) & (arr_4 > arr_3)]

In [38]:
np.testing.assert_array_equal(find_thresholds([0], [0]), find_thresholds_np(np.array([0]), np.array([0])))
np.testing.assert_array_equal(find_thresholds([1], [1]), find_thresholds_np(np.array([1]), np.array([1])))
np.testing.assert_array_equal(
    find_thresholds([0, 0, 1, 1], [0, 0, 1, 1]), 
    find_thresholds_np(np.array([0, 0, 1, 1]), np.array([0, 0, 1, 1]))
)
np.testing.assert_array_equal(
    find_thresholds([0, 0, 1, 0, 0, 1, 1, 1], [0, 0, 0, 0, 0, 1, 1, 1]),
    find_thresholds_np(np.array([0, 0, 1, 0, 0, 1, 1, 1]), np.array([0, 0, 0, 0, 0, 1, 1, 1]))
)

### Разные действия с матрицами (3 балла)

Задание 22.

Дана матрица размера $(32, 3, 16, 16)$, заполненная случайными числами от 0 до 9. При помощи **ровно пяти** преобразований приведите её к виду $(32, 1)$. При выполнении задания **можно** создавать вспомогательные матрицы!

In [39]:
data = np.random.randint(0, 10, size=(32, 3, 16, 16))

# (∩｀-´)⊃━☆ﾟ.*･｡ﾟ
# Преобразование 1
k1 = np.random.randint(0, 10, size=(16))
# Преобразование 2
data = np.matmul(data, k1)
# Преобразование 3
data = np.matmul(data, k1)
# Преобразование 4
k2 = np.random.randint(0, 10, size=(3, 1))
# Преобразование 5
data = np.matmul(data, k2)

print(data.shape)

assert data.shape == (32, 1)

(32, 1)


Задание 23.

Даны две матрицы $m_1$ размером $(32, 256)$ и $m_2$ размером $(32, 512)$, а также две вспомогательные матрицы $W_1$ размером $(256, 32)$ и $W_2$ размером $(512, 16)$. Используя все данные матрицы, сделайте так, чтобы на выходе получилась **ровно одна** матрица размером $(32, 32)$

In [40]:
m1 = np.random.randint(0, 10, size=(32, 256))
m2 = np.random.randint(0, 10, size=(32, 512))
W1 = np.random.randint(0, 10, size=(256, 32))
W2 = np.random.randint(0, 10, size=(512, 16))


temp1 = np.matmul(m1, W1)
temp2 = np.matmul(W2.T, m2.T)
temp3 = np.matmul(m2, W2)
result = np.matmul(temp1, np.matmul(temp3, temp2))
# result = (m1.dot(W1)).dot(m2.dot(W2).dot((W2.T.dot(m2.T))))
print(result.shape)

assert result.shape == (32, 32)

(32, 32)


Задание 24.

Последнее испытание для юного мага матриц - приведите полученную на последнем шаге матрицу к виду $(32, 3)$ и сделайте так, чтобы все значения в этой матрице были в промежутке от $0$ до $1$

In [41]:
'''
Не понял, какие матрицы использовать, поэтому два варианта: 
1. подсчитал просто статистику, сделал из неё матрицу (потом надо её транспонировать)
2. создал матрицу из единиц размером (32, 3) и умножил
и потом применил min-max scale.
'''

# result = np.vstack((result.min(axis = 0), result.max(axis = 0), result.mean(axis = 0)))
# result = np.transpose(result)

result = np.matmul(result, np.ones(shape=(32, 3)))
result = (result - result.min()) / (result.max() - result.min())
print(result.shape)

assert ((result >= 0) & (result <= 1)).all()

(32, 3)
