In [1]:
import numpy as np

# Numpy

#### 1.Создать вектор (одномерный массив) размера 100, заполненный нулями

In [2]:
np.zeros(shape = (100))

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

#### 2.Создать вектор размера 100, заполненный единицами

In [3]:
np.ones(shape = (100))

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

#### 3.Создать вектор размера 100, заполненный числом 3

In [4]:
np.linspace(3, 3, 100)

array([3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3.,
       3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3.,
       3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3.,
       3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3.,
       3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3.,
       3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3.])

#### 4. Как получить документацию о функции numpy.add из командной строки?

In [ ]:
?np.add

#### 5. Поменять 2 строки в матрице

In [5]:
matrix_1 = np.array([[1, 2, 3], [4, 5, 6]])

In [6]:
matrix_1

array([[1, 2, 3],
       [4, 5, 6]])

In [7]:
matrix_1[[0, 1]] = matrix_1[[1, 0]]

In [8]:
matrix_1

array([[4, 5, 6],
       [1, 2, 3]])

#### 6. Создать вектор со значениями от 10 до 100

In [9]:
np.arange(10, 101, 1)

array([ 10,  11,  12,  13,  14,  15,  16,  17,  18,  19,  20,  21,  22,
        23,  24,  25,  26,  27,  28,  29,  30,  31,  32,  33,  34,  35,
        36,  37,  38,  39,  40,  41,  42,  43,  44,  45,  46,  47,  48,
        49,  50,  51,  52,  53,  54,  55,  56,  57,  58,  59,  60,  61,
        62,  63,  64,  65,  66,  67,  68,  69,  70,  71,  72,  73,  74,
        75,  76,  77,  78,  79,  80,  81,  82,  83,  84,  85,  86,  87,
        88,  89,  90,  91,  92,  93,  94,  95,  96,  97,  98,  99, 100])

#### 7. Развернуть вектор (первый становится последним)

In [10]:
arr = np.array([1, 2, 3])
print("Вектор: ", arr)
print("Развёрнутый вектор: ", arr[::-1])

Вектор:  [1 2 3]
Развёрнутый вектор:  [3 2 1]


#### 8. Создать матрицу (двумерный массив) 4x4 со значениями от 0 до 16

In [ ]:
# Массив 4 на 4 можно составить только от 0 до 15, или от 1 до 16

np.arange(0, 16, 1).reshape((4, 4))

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

#### 9.  Дан вектор [1, 2, 3, 4, 5], построить новый вектор с тремя нулями между каждым значением

In [245]:
x = np.array([1, 2, 3, 4, 5])
y = np.zeros(len(x) + (len(x)-1)*(3))
y[::4] = x
print(y)

[1. 0. 0. 0. 2. 0. 0. 0. 3. 0. 0. 0. 4. 0. 0. 0. 5.]


#### 10. Создать 3x3 единичную матрицу

In [14]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

#### 11. Создать массив 3x3x3 со случайными значениями

In [12]:
np.random.random_sample(size=(3, 3, 3))

array([[[0.14332023, 0.69987415, 0.9752143 ],
        [0.87738333, 0.67798887, 0.71766752],
        [0.19462537, 0.13369639, 0.279408  ]],

       [[0.39806419, 0.05272859, 0.7916119 ],
        [0.41684427, 0.89696537, 0.54110536],
        [0.98600479, 0.96285496, 0.89262503]],

       [[0.82782339, 0.77961461, 0.10437943],
        [0.08805123, 0.20841554, 0.07067671],
        [0.75407684, 0.46383519, 0.58937594]]])

#### 12. Создать массив 10x10 со случайными значениями, найти минимум и максимум

In [13]:
array = np.random.random_sample(size=(10, 10))
print("-"* 20)
print(array)
print("-" * 20)
print("Минимум: ", np.min(array))
print("Максимум: ", array.max())

--------------------
[[0.20055398 0.64362303 0.5867954  0.57610491 0.29899902 0.9726757
  0.12845586 0.63093771 0.11974665 0.84277017]
 [0.17662694 0.21888674 0.52019107 0.23684686 0.49647062 0.19186406
  0.86072566 0.3729147  0.61313768 0.44873969]
 [0.75439666 0.22074131 0.78710916 0.95374664 0.61660517 0.52903648
  0.83829078 0.42945862 0.36642644 0.92667506]
 [0.83584588 0.56911831 0.73139658 0.32411973 0.31441711 0.63674907
  0.53008285 0.90054541 0.98473769 0.79456899]
 [0.34100745 0.87418633 0.61010417 0.41314322 0.24184912 0.47871527
  0.78029556 0.95061032 0.67732588 0.25407681]
 [0.11301277 0.8133826  0.53401205 0.37070275 0.4084496  0.86099654
  0.07349031 0.21091102 0.25888347 0.22827184]
 [0.02777197 0.02014399 0.0026312  0.98359628 0.00573572 0.911034
  0.81910609 0.19441928 0.63439457 0.56948316]
 [0.39677185 0.51139952 0.63576937 0.60690189 0.12005455 0.81998542
  0.78098537 0.6969822  0.65770324 0.65235127]
 [0.99457595 0.55155507 0.71810215 0.97045873 0.22361867 0.307

#### 13. Создать случайный вектор размера 30 и найти среднее значение всех элементов

In [15]:
array = np.random.random_sample(size=30)
print("-"* 20)
print(array)
print("-" * 20)
print("Среднее: ", np.mean(array))

--------------------
[0.33379983 0.16987228 0.19284623 0.97729417 0.16957272 0.61791406
 0.00109935 0.4471849  0.78180806 0.17155547 0.39361448 0.14388528
 0.1315136  0.48799316 0.99107821 0.45895041 0.62351435 0.44052385
 0.93192708 0.31022085 0.11149401 0.499863   0.6851572  0.25125307
 0.15954644 0.64391369 0.55015131 0.17379258 0.23734312 0.27408001]
--------------------
Среднее:  0.4120920917080398


#### 14. Создать матрицу с 0 внутри, и 1 на границах

In [235]:
x = np.ones((10,10))
x[1:-1,1:-1] = 0
print(x)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


#### 15. Удивите меня в этом задании, покажите какое нибудь класное преобразование в numpy (не идет в зачет)

In [49]:
# Сдвиг трёхмерного массива
x = np.arange(0, 9, 1).reshape((3, 3))
print("Исходный массив:")
print(x)
print("-" * 20)
print("После сдвига на 2: ")
print(np.roll(x, 2))

Исходный массив:
[[0 1 2]
 [3 4 5]
 [6 7 8]]
--------------------
После сдвига на 2: 
[[7 8 0]
 [1 2 3]
 [4 5 6]]


#### 16. Создать 5x5 матрицу с 1,2,2,4 под диагональю

In [238]:
np.diag(np.array([1, 2, 2, 4]), k=-1)

array([[0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 2, 0, 0],
       [0, 0, 0, 4, 0]])

#### 17. Создать 8x8 матрицу и заполнить её в шахматном порядке

In [236]:
x = np.zeros((8,8), dtype=int)
x[1::2,::2] = 1
x[::2,1::2] = 1
print(x)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


#### 18. Дан массив размерности (6,7,8). Каков индекс (x,y,z) сотого элемента?

In [234]:
np.unravel_index(indices = 100, shape = (6,7,8))

(1, 5, 4)

#### 19. Создать 8x8 матрицу и заполнить её в шахматном порядке, используя функцию tile

In [43]:
np.tile(np.hstack((np.tile((0, 1), 4), (np.tile((1, 0), 4)))), 4).reshape((8, 8))

array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0]])

#### 20. Перемножить матрицы 5x3 и 3x2

In [44]:
matr53 = np.ones(shape=(5, 3))
matr32 = np.array([[1, 2], [3, 4], [5, 6]])

matr53.dot(matr32)

array([[ 9., 12.],
       [ 9., 12.],
       [ 9., 12.],
       [ 9., 12.],
       [ 9., 12.]])

#### 21. Дан массив, поменять знак у элементов, значения которых между 3 и 8

In [63]:
x = np.random.randint(0, 10, size=(5, ))
print("Исходный массив: ", x)

x[(x >= 3) & (x <= 8)] *= -1
print("Результат: ", x)

Исходный массив:  [2 3 5 1 6]
Результат:  [ 2 -3 -5  1 -6]


#### 23. Создать 5x5 матрицу со значениями в строках от 0 до 4

In [66]:
np.tile(np.arange(0, 5, 1), 5).reshape((5,5))

array([[0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4]])

#### 24. Есть генератор, сделать с его помощью массив

In [67]:
np.fromiter(range(0, 20), dtype = int, count = -1)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

#### 25. Создать вектор размера 10 со значениями от 0 до 1, не включая ни то, ни другое

In [69]:
0.999 * np.random.random(size = (10, )) + 0.001

array([0.3056831 , 0.77746217, 0.95796552, 0.46513661, 0.97192676,
       0.29869791, 0.00304926, 0.85438468, 0.4727725 , 0.31275817])

#### 26. Отсортировать вектор

In [68]:
x = np.random.randint(low = 0, high = 9, size = (20, ))
print("Исходный массив: ", x)
print("Отсортировнный массив: ", np.sort(x))

Исходный массив:  [2 6 8 5 1 3 6 3 2 2 3 2 4 4 8 5 1 4 6 6]
Отсортировнный массив:  [1 1 2 2 2 2 3 3 3 4 4 4 5 5 6 6 6 6 8 8]


#### 27. Проверить, одинаковы ли 2 numpy массива

In [76]:
print("Исходные массивы: ")
x = np.array([1, 2, 3])
y = np.array([1, 2, 3])

print(x)
print(y)
print("-" * 20)

print("Равны ли эти массивы? - ", (x == y).all())
print("-" * 20)
print("Изменим массив y")
y = np.array([1, 2, 4])
print(y)
print("Равны ли эти массивы? - ", (x == y).all())

Исходные массивы: 
[1 2 3]
[1 2 3]
--------------------
Равны ли эти массивы? -  True
--------------------
Изменим массив y
[1 2 4]
Равны ли эти массивы? -  False


#### 28. Сделать массив неизменяемым

In [77]:
a = np.arange(10)
a.flags.writeable = False
a[0] = 1

ValueError: ignored

#### 29. Найти n наибольших значений в массиве

In [80]:
x = np.random.randint(low = 0, high = 20, size = (20, ))
print("Исходный массив: ")
print(x)
print("-" * 20)
print("Первые N = 5 значений", np.sort(x)[::-1][:5])

Исходный массив: 
[ 1  5 16  1  8  2  2  1  5 14  1  5  7 18  5  9  5  7  8 19]
--------------------
Первые N = 5 значений [19 18 16 14  9]


#### 30. Заменить максимальный элемент на ноль

In [86]:
x = np.random.randint(low = 0, high = 20, size = (20, ))
print("Исходный массив: ")
print(x)
print("-" * 20)
print("Индекс масимального элемента (общий размер 20, индексы начиная с 0): ", np.argmax(x))
x[np.argmax(x)] = 0
print("После преобразования: ", x)

Исходный массив: 
[12  5 17  3  8  1 10  1  0  6 12 14  3 14 13 11  0 16  6 19]
--------------------
Индекс масимального элемента (общий размер 20, индексы начиная с 0):  19
После преобразования:  [12  5 17  3  8  1 10  1  0  6 12 14  3 14 13 11  0 16  6  0]


#### 31. Создать структурированный массив с координатами x, y на сетке в квадрате [0,1]x[0,1]

In [232]:
grid = np.zeros(shape = (5, 5), dtype = [('x',float),('y',float)])
grid['x'], grid['y'] = np.meshgrid(np.linspace(0,1,5),
                             np.linspace(0,1,5))
print(grid[::-1])

[[(0.  , 1.  ) (0.25, 1.  ) (0.5 , 1.  ) (0.75, 1.  ) (1.  , 1.  )]
 [(0.  , 0.75) (0.25, 0.75) (0.5 , 0.75) (0.75, 0.75) (1.  , 0.75)]
 [(0.  , 0.5 ) (0.25, 0.5 ) (0.5 , 0.5 ) (0.75, 0.5 ) (1.  , 0.5 )]
 [(0.  , 0.25) (0.25, 0.25) (0.5 , 0.25) (0.75, 0.25) (1.  , 0.25)]
 [(0.  , 0.  ) (0.25, 0.  ) (0.5 , 0.  ) (0.75, 0.  ) (1.  , 0.  )]]


#### 32. Из двух массивов сделать матрицу Коши C (Cij = 1/(xi - yj))

In [92]:
N = 5
x = np.random.randint(low = 1, high = 20, size = (N, ))
y = np.random.randint(low = 1, high = 20, size = (N, ))

print("Исходные массивы: ")
print(x)
print(y)

C = 1.0 / (x.reshape((-1,1)) - y)
print("Матрица Коши: ")
print(C)

Исходные массивы: 
[10 15 15  5 11]
[ 9  8 16  6 17]
Матрица Коши: 
[[ 1.          0.5        -0.16666667  0.25       -0.14285714]
 [ 0.16666667  0.14285714 -1.          0.11111111 -0.5       ]
 [ 0.16666667  0.14285714 -1.          0.11111111 -0.5       ]
 [-0.25       -0.33333333 -0.09090909 -1.         -0.08333333]
 [ 0.5         0.33333333 -0.2         0.2        -0.16666667]]


#### 33. Найти минимальное и максимальное значение, принимаемое каждым числовым типом numpy

In [110]:
print(np.finfo(np.float))
print(np.finfo(np.float128))
print(np.finfo(np.float32))

print(np.iinfo(np.int32))
print(np.iinfo(np.int64))
print(np.iinfo(np.int16))

Machine parameters for float64
---------------------------------------------------------------
precision =  15   resolution = 1.0000000000000001e-15
machep =    -52   eps =        2.2204460492503131e-16
negep =     -53   epsneg =     1.1102230246251565e-16
minexp =  -1022   tiny =       2.2250738585072014e-308
maxexp =   1024   max =        1.7976931348623157e+308
nexp =       11   min =        -max
---------------------------------------------------------------

Machine parameters for float128
---------------------------------------------------------------
precision =  18   resolution = 1e-18
machep =    -63   eps =        1.084202172485504434e-19
negep =     -64   epsneg =     5.42101086242752217e-20
minexp = -16382   tiny =       3.3621031431120935063e-4932
maxexp =  16384   max =        1.189731495357231765e+4932
nexp =       15   min =        -max
---------------------------------------------------------------

Machine parameters for float32
---------------------------------------

#### 34. Напечатать все значения в массиве

In [114]:
x = np.random.randint(low = 0, high = 20, size = (1000, ))

print("Вывод всех значений: ")
with np.printoptions(threshold=np.inf):
    print(x)

Вывод всех значений: 
[ 6 14 10  5  7 19 15  0  0  9  0  5  9 15  0  0  9  4  0 13  0 16  0 11
  8 11  3  5 15 14 13  9  9 14 13  6 18 11 13 19 17  3 13 12 19 13 10  5
 13  1 19  9  0  9  0 14  9 18 10  7 18  0  5  2  8 13  9  5  7 13 19 18
  1  8  7 16  9  4  4 18 17 13 17  2  8 15  5  7  7  3  1 17 17 10  7 12
 14  1 15  7  3 17 12 12 15 12  1  7 14  1 11  2 19  5  6  0 13  4  7 13
 16 16  3 12  2  5  0  6 19  5 11  4  5  7 10  6  5 10 13  6 19 15  9 13
 13  9 14 13  8 12 14 17 10  5  7  8  5 11 16 18 17  7  6  8  9 17  7 16
 17  0  7 16 12 16  4  3  5 16  0 13  4  0  0  9 19  4 15  7  7  2 15  7
 18  5  8  3 12 17 11  8  1 11 17 19  1 14  7 10  7  9  3 16  3 10  2  8
 15 15  3 19  9  9  2 16  5 15  0  8  7  2 15  1 13  1  0  1 11  6  6  1
  9  2 18 15 17  1 18 14  2  5 14  7 11  7  2 15 10  0 13 10 14  7  8  1
  8 12  9 19 16 17 12 13 19 17 13 17  9 11  0 16  0 16 19  3 11  2  6  8
  1 12 14 19  1  6  7 18 17  8  0 13  7  3  4 18 11 19 12  4 15  4  9  7
  3  3  6 16 17 12 14 13  3  

#### 35. Найти ближайшее к заданному значению число в заданном массиве

In [115]:
X = 15
x = np.random.randint(low = 0, high = 100, size = (10, ))
print("Исходный массив: ")
print(x)
print("-" * 20)
print("Заданное число: ", X)
print("Индекс ближайшего элемента и его значение(общий размер 100, индексы начиная с 0): ", \
      np.argmin(np.abs(x - X)), x[np.argmin(np.abs(x - X))])

Исходный массив: 
[63 18 59 28 26 88 57 49 63 33]
--------------------
Заданное число:  15
Индекс ближайшего элемента и его значение(общий размер 100, индексы начиная с 0):  1 18


#### 36. Преобразовать массив из float в int

In [119]:
x = 5 * np.random.random(size = (10, )) - 5
print(x)

print("После приведения: ")
print(x.astype(int))

[-4.64937254 -2.71670896 -0.63444909 -1.15213333 -0.19554989 -1.68295947
 -2.63585428 -1.37356324 -0.15206929 -3.41160093]
После приведения: 
[-4 -2  0 -1  0 -1 -2 -1  0 -3]


#### 37. Каков эквивалент функции enumerate для numpy массивов?

In [122]:
y = np.random.randint(low = 1, high = 20, size = (5, 2))

for index, value in np.ndenumerate(y):
  print(index, value)

(0, 0) 9
(0, 1) 2
(1, 0) 11
(1, 1) 11
(2, 0) 17
(2, 1) 18
(3, 0) 11
(3, 1) 13
(4, 0) 6
(4, 1) 12


#### 38. Случайно расположить p элементов в 2D массив

In [227]:
N = 5
x = np.zeros((N,N))
p = 7
np.put(x, np.random.choice(range(N * N), p, replace=False), 1)
print(x)

[[0. 0. 0. 1. 1.]
 [0. 0. 1. 0. 1.]
 [0. 0. 0. 0. 1.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]]


#### 39. Отнять среднее из каждой строки в матрице

In [132]:
y = np.random.randint(low = 1, high = 20, size = (3, 3))
print("Исходная матрица: ")
print(y)
print("После отнятия среднего по каждой строке: ")
y - np.mean(y, axis = 1).reshape(3, -1)

Исходная матрица: 
[[17  8 12]
 [ 2  6 12]
 [ 4  4  8]]
После отнятия среднего: 


array([[ 4.66666667, -4.33333333, -0.33333333],
       [-4.66666667, -0.66666667,  5.33333333],
       [-1.33333333, -1.33333333,  2.66666667]])

#### 40. Отсортировать матрицу по n-ому столбцу

In [207]:
y = np.random.randint(low = 1, high = 20, size = (3, 3))
print("Исходная матрица: ")
print(y)
N = 1 
print("После сортировке по второму столбцу (индексация с 0): ")
print(y[y[:, N].argsort()])

Исходная матрица: 
[[18  6  6]
 [ 6 17 19]
 [11 12  9]]
После сортировке по второму столбцу (индексация с 0): 
[[18  6  6]
 [11 12  9]
 [ 6 17 19]]


#### 41. Определить, есть ли в 2D массиве нулевые столбцы

In [205]:
y = np.random.randint(low = 0, high = 2, size = (3, 3))
print("Исходная матрица: ")
print(y)

t = y.any(axis=0)
t[t == False].shape[0] > 0

Исходная матрица: 
[[1 0 0]
 [0 0 1]
 [1 0 0]]


True

#### 42. Дан массив, добавить 1 к каждому элементу с индексом, заданным в другом массиве (осторожно с повторами)

In [152]:
x = np.random.randint(low = 1, high = 20, size = (10, ))
ind = np.array([1, 3, 5])
print("Исходный массив: ")
print(x)

print("Индексы для добавления: ")
print(ind)
x += np.bincount(ind, minlength=len(x))
print("Результат: ")
print(x)

Исходный массив: 
[ 3 18  5  9  2  7 13 14 16  4]
Индексы для добавления: 
[1 3 5]
Результат: 
[ 3 19  5 10  2  8 13 14 16  4]


#### 43. Дан массив (w,h,3) (картинка) dtype=ubyte, посчитать количество различных цветов

In [287]:
w = h = 2
pic = np.random.randint(0, 2, (h,w,3)).astype(np.ubyte)
print("Картинка: ")
print(pic)

print("Количество разных цветов: ")
np.unique(np.apply_along_axis(lambda x: str(x), 2, pic), 2)[0].shape[0]

Картинка: 
[[[0 1 1]
  [1 0 1]]

 [[0 1 0]
  [0 1 1]]]
Количество разных цветов: 


3

#### 44. Дан четырехмерный массив, посчитать сумму по последним двум осям

In [211]:
x = np.random.randint(low = 1, high = 20, size = (2, 3, 4, 5))
print("Исходный массив: ")
print(x)
print("Результат: ")
print(x.reshape(x.shape[:-2] + (-1, )).sum(axis=0))

Исходный массив: 
[[[[ 4 14  8  5  3]
   [ 3 16 19 12 12]
   [ 3  5 14 17 18]
   [16 10  5 13  2]]

  [[18  1 16  3  5]
   [13  6 11  9 17]
   [ 5 15 10 19  3]
   [19 14 14 19  6]]

  [[14  6 16 19 10]
   [ 1  1 18 17 10]
   [15  3 17  1  4]
   [14 17 10 13 17]]]


 [[[ 3  4  7 15 19]
   [15 11 16  7 11]
   [15  6  4 11 13]
   [ 2  2 18  3 12]]

  [[ 5  1 16  8  8]
   [ 8  2  6  8 14]
   [ 2  1  2  3 14]
   [ 5  7 18 13  8]]

  [[19 12 18  7  2]
   [ 5 17 16  8 12]
   [19  9  3  8 19]
   [17  3 12  1  6]]]]
Результат: 
[[ 7 18 15 20 22 18 27 35 19 23 18 11 18 28 31 18 12 23 16 14]
 [23  2 32 11 13 21  8 17 17 31  7 16 12 22 17 24 21 32 32 14]
 [33 18 34 26 12  6 18 34 25 22 34 12 20  9 23 31 20 22 14 23]]
